import { useI18n } from '../i18n/I18nContext';
import type { FullAnalysisData, PayoffCell } from '../types';

const utility = (value: number) => Number(value).toFixed(2);
export function AnalysisPanels({ data, tab }: { data: FullAnalysisData; tab: string }) { if (tab === 'analysis') return <Analysis data={data} />; if (tab === 'uncertainty') return <Uncertainty data={data} />; if (tab === 'arbitration') return <Arbitration data={data} />; if (tab === 'simulation') return <Simulation data={data} />; return <Results data={data} />; }

function Analysis({ data }: { data: FullAnalysisData }) { const { t } = useI18n(); const nash = new Set(data.pure_nash_equilibria.map((item) => item.outcome_id)); const pareto = new Set(data.pareto_optimal_outcomes.map((item) => item.outcome_id)); return <div className="stack"><h2>{t('payoffMatrix')}</h2><p className="muted">{t('rows')}: {data.payoff_matrix.row_player}. {t('columns')}: {data.payoff_matrix.column_player}. {t('utilitiesBackend')}</p><div className="matrix-wrap"><table className="matrix"><caption>{t('matrixCaption')}</caption><thead><tr><th></th>{data.payoff_matrix.column_strategies.map((strategy) => <th key={strategy}>{strategy}</th>)}</tr></thead><tbody>{data.payoff_matrix.row_strategies.map((row) => <tr key={row}><th>{row}</th>{data.payoff_matrix.cells.filter((cell) => cell.row_strategy === row).map((cell) => <MatrixCell key={cell.outcome_id} cell={cell} nash={nash.has(cell.outcome_id)} pareto={pareto.has(cell.outcome_id)} />)}</tr>)}</tbody></table></div><div className="legend"><span className="badge nash">{t('nash')}: {Array.from(nash).join(', ') || t('none')}</span><span className="badge pareto">{t('pareto')}: {Array.from(pareto).join(', ') || t('none')}</span></div><p className="explanation">{data.prisoners_dilemma.detected ? t('pdDetected') : t('pdNotDetected')}</p><h3>{t('dominanceBestResponses')}</h3><ul>{data.dominated_strategies.map((item) => <li key={`${item.player_id}-${item.strategy}`}>{item.player_id}: {item.strategy} is {item.kind.toLowerCase()} {t('dominatedBy')} {item.dominated_by}.</li>)}</ul></div>; }
function MatrixCell({ cell, nash, pareto }: { cell: PayoffCell; nash: boolean; pareto: boolean }) { const { t } = useI18n(); return <td className={`${nash ? 'nash-cell' : ''} ${pareto ? 'pareto-cell' : ''}`}><strong>{utility(cell.utilities[0])}</strong> / <strong>{utility(cell.utilities[1])}</strong><div>{nash && <span className="cell-label">{t('nash')}</span>}{pareto && <span className="cell-label">{t('pareto')}</span>}</div></td>; }
function Uncertainty({ data }: { data: FullAnalysisData }) { const { t } = useI18n(); return <div className="stack"><h2>{t('gamesAgainstNature')}</h2><p className="muted">{t('allSixCriteria')}</p><div className="method-grid">{data.uncertainty_analysis.methods.map((method) => <article className="card" key={method.id}><h3>{method.id}</h3><p className="recommend">{t('recommended')}: {method.recommended.join(', ')}</p><p>{method.explanation}</p><dl>{Object.entries(method.scores).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{utility(value)}</dd></div>)}</dl></article>)}</div><h3>{t('regretMatrix')}</h3><pre className="data-table">{JSON.stringify(data.uncertainty_analysis.regret_matrix, null, 2)}</pre></div>; }
function Arbitration({ data }: { data: FullAnalysisData }) { const { t } = useI18n(); const result = data.arbitration_result; const selected = result.selected; return <div className="stack"><h2>{t('nashArbitration')}</h2><p className="muted">{t('arbitrationDescription')}</p><div className="allocation-grid"><div className="card"><h3>{t('disagreement')}</h3><p>[{result.disagreement.join(', ')}]</p><p>{t('qualifyingCandidates')}: {result.qualifying_candidates_count.toLocaleString()}</p></div>{selected ? <div className="card success"><h3>{t('selectedAllocation')}</h3><p>{t('energy')}: {selected.allocation.energy_kwh.join(', ')} kWh</p><p>{t('hours')}: {selected.allocation.hours.join(', ')}</p><p>{t('costShares')}: {selected.cost_shares.map((share) => `${(share * 100).toFixed(0)}%`).join(' / ')}</p><p>{t('utilities')}: {selected.utilities.map(utility).join(' / ')}</p><p>{t('nashProduct')}: {selected.nash_product.toFixed(4)}</p><p>{result.ties.length ? `${t('ties')}: ${result.ties.join(', ')}` : t('uniqueMaximum')}</p></div> : <div className="card error"><h3>{t('noQualifyingAgreement')}</h3></div>}</div><ul>{result.explanations.map((text) => <li key={text}>{text}</li>)}</ul></div>; }
function Simulation({ data }: { data: FullAnalysisData }) { const { t } = useI18n(); return <div className="stack"><h2>{t('repeatedGameTitle')}</h2>{data.repeated_game_result ? <pre className="data-table">{JSON.stringify(data.repeated_game_result, null, 2)}</pre> : <div className="card"><p>{t('noRepeatedGame')}</p><p>{t('supportedStrategies')}: ALWAYS_COOPERATE, ALWAYS_CLAIM_MORE, TIT_FOR_TAT, FORGIVING_TIT_FOR_TAT, RANDOM.</p></div>}</div>; }
function Results({ data }: { data: FullAnalysisData }) { const { t } = useI18n(); return <div className="stack"><h2>{t('recommendationTheory')}</h2><div className="card success"><h3>{t('cooperativeRecommendation')}</h3><p>{data.final_recommendation.explanation}</p><p>{t('outcomeId')}: {data.final_recommendation.outcome_id ?? t('arbitrationNotMm')}</p></div><h3>{t('explanations')}</h3><ul>{data.explanations.map((item) => <li key={item}>{item}</li>)}</ul><h3>{t('assumptionsScope')}</h3><ul><li>{t('exactlyTwoScope')}</li><li>{t('chapter17Excluded')}</li><li>{t('penaltiesScope')}</li><li>{t('decisionSupportScope')}</li><li>{t('stableBetterScope')}</li></ul>{data.warnings?.length ? <><h3>{t('warnings')}</h3><ul>{data.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></> : null}</div>; }
