import type { FullAnalysisData, PayoffCell } from '../types';
const utility = (value: number) => Number(value).toFixed(2);

export function AnalysisPanels({ data, tab }: { data: FullAnalysisData; tab: string }) {
  if (tab === 'analysis') return <Analysis data={data} />;
  if (tab === 'uncertainty') return <Uncertainty data={data} />;
  if (tab === 'arbitration') return <Arbitration data={data} />;
  if (tab === 'simulation') return <Simulation data={data} />;
  return <Results data={data} />;
}

function Analysis({ data }: { data: FullAnalysisData }) {
  const nash = new Set(data.pure_nash_equilibria.map((item) => item.outcome_id)); const pareto = new Set(data.pareto_optimal_outcomes.map((item) => item.outcome_id));
  return <div className="stack"><h2>Payoff matrix & equilibrium</h2><p className="muted">Rows: {data.payoff_matrix.row_player}. Columns: {data.payoff_matrix.column_player}. Utilities are backend results, not money.</p><div className="matrix-wrap"><table className="matrix"><caption>Two-player payoff matrix. Each cell is P1 / P2.</caption><thead><tr><th></th>{data.payoff_matrix.column_strategies.map((strategy) => <th key={strategy}>{strategy}</th>)}</tr></thead><tbody>{data.payoff_matrix.row_strategies.map((row) => <tr key={row}><th>{row}</th>{data.payoff_matrix.cells.filter((cell) => cell.row_strategy === row).map((cell) => <MatrixCell key={cell.outcome_id} cell={cell} nash={nash.has(cell.outcome_id)} pareto={pareto.has(cell.outcome_id)} />)}</tr>)}</tbody></table></div><div className="legend"><span className="badge nash">Nash: {Array.from(nash).join(', ') || 'none'}</span><span className="badge pareto">Pareto: {Array.from(pareto).join(', ') || 'none'}</span></div><p className="explanation">{data.prisoners_dilemma.detected ? 'Prisoner’s Dilemma detected: CLAIM_MORE dominates for both players, while CC is Pareto-superior to stable MM.' : 'The backend did not classify this matrix as a Prisoner’s Dilemma.'}</p><h3>Dominance and best responses</h3><ul>{data.dominated_strategies.map((item) => <li key={`${item.player_id}-${item.strategy}`}>{item.player_id}: {item.strategy} is {item.kind.toLowerCase()} dominated by {item.dominated_by}.</li>)}</ul></div>;
}
function MatrixCell({ cell, nash, pareto }: { cell: PayoffCell; nash: boolean; pareto: boolean }) { return <td className={`${nash ? 'nash-cell' : ''} ${pareto ? 'pareto-cell' : ''}`}><strong>{utility(cell.utilities[0])}</strong> / <strong>{utility(cell.utilities[1])}</strong><div>{nash && <span className="cell-label">Nash</span>}{pareto && <span className="cell-label">Pareto</span>}</div></td>; }
function Uncertainty({ data }: { data: FullAnalysisData }) { const methods = data.uncertainty_analysis.methods; return <div className="stack"><h2>Games Against Nature</h2><p className="muted">All six criteria and regret values are supplied by the backend.</p><div className="method-grid">{methods.map((method) => <article className="card" key={method.id}><h3>{method.id}</h3><p className="recommend">Recommended: {method.recommended.join(', ')}</p><p>{method.explanation}</p><dl>{Object.entries(method.scores).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{utility(value)}</dd></div>)}</dl></article>)}</div><h3>Regret matrix</h3><pre className="data-table">{JSON.stringify(data.uncertainty_analysis.regret_matrix, null, 2)}</pre></div>; }
function Arbitration({ data }: { data: FullAnalysisData }) { const result = data.arbitration_result; const selected = result.selected; return <div className="stack"><h2>Nash arbitration</h2><p className="muted">This cooperative recommendation is distinct from the one-shot MM equilibrium.</p><div className="allocation-grid"><div className="card"><h3>Disagreement</h3><p>[{result.disagreement.join(', ')}]</p><p>Qualifying candidates: {result.qualifying_candidates_count.toLocaleString()}</p></div>{selected ? <div className="card success"><h3>Selected allocation</h3><p>Energy: {selected.allocation.energy_kwh.join(', ')} kWh</p><p>Hours: {selected.allocation.hours.join(', ')}</p><p>Cost shares: {selected.cost_shares.map((share) => `${(share * 100).toFixed(0)}%`).join(' / ')}</p><p>Utilities: {selected.utilities.map(utility).join(' / ')}</p><p>Nash product: {selected.nash_product.toFixed(4)}</p><p>{result.ties.length ? `Ties: ${result.ties.join(', ')}` : 'Unique maximum; no tie.'}</p></div> : <div className="card error"><h3>No qualifying agreement</h3></div>}</div><ul>{result.explanations.map((text) => <li key={text}>{text}</li>)}</ul></div>; }
function Simulation({ data }: { data: FullAnalysisData }) { return <div className="stack"><h2>Repeated game</h2>{data.repeated_game_result ? <pre className="data-table">{JSON.stringify(data.repeated_game_result, null, 2)}</pre> : <div className="card"><p>No repeated-game run was requested. This dashboard does not invent repeated-game scores.</p><p>Supported backend strategies: ALWAYS_COOPERATE, ALWAYS_CLAIM_MORE, TIT_FOR_TAT, FORGIVING_TIT_FOR_TAT, RANDOM.</p></div>}</div>; }
function Results({ data }: { data: FullAnalysisData }) { return <div className="stack"><h2>Recommendation and theory</h2><div className="card success"><h3>Cooperative recommendation</h3><p>{data.final_recommendation.explanation}</p><p>Outcome ID: {data.final_recommendation.outcome_id ?? 'none — arbitration is not MM'}</p></div><h3>Explanations</h3><ul>{data.explanations.map((item) => <li key={item}>{item}</li>)}</ul><h3>Assumptions and scope</h3><ul><li>Exactly two players; Straffin Chapters 1–16, including Chapter 16.</li><li>Chapter 17+ methods are excluded. Utility weights are prototype assumptions.</li><li>Overload penalty is 5; violation penalty is 0; disagreement baseline is [0,0].</li><li>This is decision support and simulation, not electrical safety or hardware control.</li><li>MM may be stable while CC and arbitration are collectively better.</li></ul>{data.warnings?.length ? <><h3>Warnings</h3><ul>{data.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></> : null}</div>; }
