import { useEffect, useMemo, useRef, useState } from 'react';
import { analyzeLive, analyzeMock, ClientError } from './api/client';
import { AnalysisPanels } from './components/AnalysisPanels';
import { ScenarioForm } from './components/ScenarioForm';
import { demoScenario } from './data/mockFixture';
import type { ApiMode, FullAnalysisData, Scenario } from './types';

const tabs = [['analysis', 'Analysis'], ['uncertainty', 'Uncertainty'], ['arbitration', 'Arbitration'], ['simulation', 'Repeated game'], ['results', 'Results / theory']];
export default function App() {
  const [scenario, setScenario] = useState<Scenario>(demoScenario); const [mode, setMode] = useState<ApiMode>(import.meta.env.VITE_DEFAULT_MODE === 'mock' ? 'mock' : 'live');
  const [analysis, setAnalysis] = useState<FullAnalysisData | null>(null); const [tab, setTab] = useState('scenario'); const [busy, setBusy] = useState(false); const [error, setError] = useState<ClientError | null>(null); const controller = useRef<AbortController | null>(null);
  useEffect(() => () => controller.current?.abort(), []);
  const modeLabel = useMemo(() => mode === 'mock' ? 'Mock Demo Data' : 'Live Backend', [mode]);
  const run = async () => { setBusy(true); setError(null); controller.current?.abort(); const next = new AbortController(); controller.current = next; try { const data = mode === 'mock' ? analyzeMock() : await analyzeLive(scenario, next.signal); if (controller.current !== next || next.signal.aborted) return; setAnalysis(data); setTab('analysis'); } catch (cause) { if (controller.current !== next || next.signal.aborted) return; if (cause instanceof DOMException && cause.name === 'AbortError') return; setError(cause instanceof ClientError ? cause : new ClientError('The analysis could not be completed.', 'malformed')); } finally { if (controller.current === next) { controller.current = null; setBusy(false); } } };
  return <div className="app"><a className="skip-link" href="#main-content">Skip to content</a><header><div className="header-inner"><div><div className="brand">Power<span>Share</span></div><p className="tagline">Game-theoretic shared backup electricity decision support</p></div><div className="mode" role="radiogroup" aria-label="Data source"><button role="radio" aria-checked={mode === 'live'} onClick={() => { setMode('live'); setAnalysis(null); setError(null); }}>Live backend</button><button role="radio" aria-checked={mode === 'mock'} onClick={() => { setMode('mock'); setAnalysis(null); setError(null); }}>Mock demo data</button></div></div><div className="mode-status" role="status">Source: {modeLabel}</div><nav aria-label="Analysis sections"><button className={tab === 'scenario' ? 'active' : ''} aria-current={tab === 'scenario' ? 'page' : undefined} onClick={() => setTab('scenario')}>Scenario</button>{tabs.map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} aria-current={tab === id ? 'page' : undefined} onClick={() => setTab(id)}>{label}</button>)}</nav></header><main id="main-content">{tab === 'scenario' ? <ScenarioForm scenario={scenario} busy={busy} error={error} onChange={setScenario} onSubmit={run} /> : analysis ? <AnalysisPanels data={analysis} tab={tab} /> : <div className="card"><h2>No analysis loaded</h2><p>Run the scenario first. Live mode never falls back silently to mock data.</p><button className="primary" onClick={() => setTab('scenario')}>Open scenario</button>{error && <p className="error" role="alert">{error.message}</p>}</div>}</main><footer>PowerShare MM · two-player Chapters 1–16 educational scope · {modeLabel}</footer></div>;
}
