import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import App from './App';
import { mockEnvelope } from './data/mockFixture';
import { dictionaryHasParity, translations } from './i18n/translations';

type Deferred<T> = { promise: Promise<T>; resolve: (value: T) => void; reject: (reason?: unknown) => void };
function deferred<T>(): Deferred<T> { let resolve!: (value: T) => void; let reject!: (reason?: unknown) => void; const promise = new Promise<T>((nextResolve, nextReject) => { resolve = nextResolve; reject = nextReject; }); return { promise, resolve, reject }; }
function fullResponse(explanation = 'request result'): Response { return new Response(JSON.stringify({ ...mockEnvelope, data: { ...mockEnvelope.data, explanations: [explanation] } }), { status: 200, headers: { 'Content-Type': 'application/json' } }); }
afterEach(() => { vi.unstubAllGlobals(); window.localStorage.clear(); document.documentElement.lang = 'en'; delete document.documentElement.dataset.theme; });
const enterWorkspace = () => fireEvent.click(screen.getByRole('button', { name: translations.en.enterWorkspace }));

describe('PowerShare dashboard contract rendering', () => {
  it('renders canonical fixture values without browser calculations', () => { render(<App />); enterWorkspace(); fireEvent.click(screen.getByRole('radio', { name: 'Mock demo data' })); fireEvent.click(screen.getByRole('button', { name: translations.en.findSharingRecommendation })); expect(screen.getAllByText('76.50').length).toBeGreaterThan(0); expect(screen.getAllByText(/Nash Equilibrium/).length).toBeGreaterThan(0); fireEvent.click(screen.getByRole('button', { name: 'Uncertainty' })); expect(screen.getAllByText('HYBRID').length).toBeGreaterThan(0); fireEvent.click(screen.getByRole('button', { name: 'Arbitration' })); expect(screen.getAllByText(/10,440/).length).toBeGreaterThan(0); expect(screen.getByText('5.5 kWh')).toBeInTheDocument(); expect(screen.getByText('4.5 kWh')).toBeInTheDocument(); });
  it('uses a live V1.1 endpoint and surfaces validation errors', async () => { const response = { error: { code: 'INVALID_CAPACITY', message: 'Available capacity must be greater than zero.', field: 'resource.capacity_kwh', correction: 'Enter a number greater than zero.' } }; vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response(JSON.stringify(response), { status: 422, headers: { 'Content-Type': 'application/json' } }))); render(<App />); enterWorkspace(); fireEvent.click(screen.getByRole('button', { name: translations.en.findSharingRecommendation })); await screen.findByText(/Available capacity must be greater than zero/); expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/api/analysis/full'), expect.objectContaining({ method: 'POST' })); });
  it('aborts request A when request B starts and ignores A AbortError', async () => { const requestA = deferred<Response>(); const requestB = deferred<Response>(); const signals: AbortSignal[] = []; const fetchMock = vi.fn((_input: RequestInfo | URL, init?: RequestInit) => { signals.push(init?.signal as AbortSignal); return signals.length === 1 ? requestA.promise : requestB.promise; }); vi.stubGlobal('fetch', fetchMock); render(<App />); enterWorkspace(); const form = screen.getByRole('button', { name: translations.en.findSharingRecommendation }).closest('form')!; fireEvent.submit(form); await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(1)); fireEvent.submit(form); await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(2)); expect(signals[0].aborted).toBe(true); expect(signals[1]).not.toBe(signals[0]); requestA.reject(new DOMException('The request was superseded.', 'AbortError')); await act(async () => requestB.resolve(fullResponse('request B'))); await waitFor(() => expect(screen.getByText('Payoff matrix & equilibrium')).toBeInTheDocument()); expect(screen.queryByRole('alert')).not.toBeInTheDocument(); });
  it('does not let a late response A overwrite completed response B', async () => { const requestA = deferred<Response>(); const requestB = deferred<Response>(); const fetchMock = vi.fn().mockImplementationOnce(() => requestA.promise).mockImplementationOnce(() => requestB.promise); vi.stubGlobal('fetch', fetchMock); render(<App />); enterWorkspace(); const form = screen.getByRole('button', { name: translations.en.findSharingRecommendation }).closest('form')!; fireEvent.submit(form); await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(1)); fireEvent.submit(form); await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(2)); expect(screen.getByRole('main')).toHaveAttribute('aria-busy', 'true'); await act(async () => requestB.resolve(fullResponse('request B'))); await waitFor(() => expect(screen.getByText('Payoff matrix & equilibrium')).toBeInTheDocument()); expect(screen.getByRole('main')).toHaveAttribute('aria-busy', 'false'); fireEvent.click(screen.getByRole('button', { name: 'Results / theory' })); await waitFor(() => expect(screen.getByText('request B')).toBeInTheDocument()); await act(async () => requestA.resolve(fullResponse('request A'))); await waitFor(() => expect(screen.getByText('request B')).toBeInTheDocument()); expect(screen.getByRole('main')).toHaveAttribute('aria-busy', 'false'); expect(screen.queryByText('request A')).not.toBeInTheDocument(); });
  it('opens the landing page first and returns home without losing preferences', () => { render(<App />); expect(screen.getByRole('heading', { name: translations.en.landingTitle })).toBeInTheDocument(); enterWorkspace(); expect(screen.getByRole('button', { name: translations.en.home })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: translations.en.home })); expect(screen.getByRole('heading', { name: translations.en.landingTitle })).toBeInTheDocument(); });
  it('localizes the major workspace sections and persists Myanmar language', () => { render(<App />); fireEvent.click(screen.getByRole('button', { name: 'မနမ' })); expect(document.documentElement.lang).toBe('my'); expect(screen.getByRole('button', { name: translations.my.enterWorkspace })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: translations.my.enterWorkspace })); expect(screen.getByText(translations.my.scenarioInput)).toBeInTheDocument(); fireEvent.click(screen.getByRole('radio', { name: translations.my.mockDemoData })); fireEvent.click(screen.getByRole('button', { name: translations.my.findSharingRecommendation })); expect(screen.getByRole('button', { name: translations.my.analysis })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: translations.my.analysis })); expect(screen.getByRole('heading', { name: translations.my.payoffMatrix })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: translations.my.uncertainty })); expect(screen.getByText(translations.my.gamesAgainstNature)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: translations.my.arbitration })); expect(screen.getByRole('heading', { name: translations.my.arbitrationTitle })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: translations.my.repeatedGame })); expect(screen.getByRole('heading', { name: translations.my.repeatedGameTitle })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: translations.my.resultsTheory })); expect(screen.getByRole('heading', { name: translations.my.recommendationTheory })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: translations.my.home })); expect(screen.getByRole('button', { name: 'မနမ' })).toHaveAttribute('aria-pressed', 'true'); });
  it('persists theme, safely falls back from invalid values, and keeps the dictionary in parity', () => { window.localStorage.setItem('powershare-theme', 'invalid'); window.localStorage.setItem('powershare-language', 'invalid'); expect(dictionaryHasParity()).toBe(true); render(<App />); expect(document.documentElement.lang).toBe('en'); fireEvent.click(screen.getByRole('button', { name: translations.en.dark })); expect(document.documentElement.dataset.theme).toBe('dark'); fireEvent.click(screen.getByRole('button', { name: translations.en.light })); expect(document.documentElement.dataset.theme).toBe('light'); });
  it('restores valid language and theme preferences after remount', () => { window.localStorage.setItem('powershare-language', 'my'); window.localStorage.setItem('powershare-theme', 'dark'); const first = render(<App />); expect(screen.getByRole('heading', { name: translations.my.landingTitle })).toBeInTheDocument(); expect(document.documentElement.lang).toBe('my'); expect(document.documentElement.dataset.theme).toBe('dark'); first.unmount(); render(<App />); expect(screen.getByRole('heading', { name: translations.my.landingTitle })).toBeInTheDocument(); expect(document.documentElement.lang).toBe('my'); });
  it('shows and clears the accessible live skeleton around a pending request', async () => { const request = deferred<Response>(); vi.stubGlobal('fetch', vi.fn(() => request.promise)); render(<App />); enterWorkspace(); const form = screen.getByRole('button', { name: translations.en.findSharingRecommendation }).closest('form')!; fireEvent.submit(form); await waitFor(() => expect(screen.getByText(translations.en.calculating)).toBeInTheDocument()); expect(screen.getByRole('main')).toHaveAttribute('aria-busy', 'true'); await act(async () => request.resolve(fullResponse('loaded'))); await waitFor(() => expect(screen.queryByText(translations.en.calculating)).not.toBeInTheDocument()); expect(screen.getByRole('main')).toHaveAttribute('aria-busy', 'false'); });
});
